# https://medium.com/@aschmelyun/the-beauty-of-docker-for-local-laravel-development-b5eb6caf0946
# https://github.com/aschmelyun/docker-compose-laravel
# https://dev.to/aschmelyun/the-beauty-of-docker-for-local-laravel-development-13c0
# https://laravel-news.com/laravel-scheduler-queue-docker

version: "3"

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "88:80"
      - "447:443"
    volumes:
      - /srv/dev-disk-by-label-shared/appdata/letsencrypt:/config
      - /srv/dev-disk-by-label-shared/appdata/laravel/src:/var/www/html
      # - /srv/dev-disk-by-label-shared/appdata/laravel/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel

  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=100
      - MYSQL_ROOT_PASSWORD=aba0954
      - TZ=Europe/London
      - MYSQL_DATABASE=cryogenic
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=aba0954
    volumes:
      - databases:/srv/dev-disk-by-label-shared/appdata/mariadb
    restart: unless-stopped
    networks:
      - laravel

  swag:
    image: linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/London
      - URL=mbhub.duckdns.org
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=2ac8057b-8d3a-4363-9afc-d5bb25ad6502
      - EMAIL=danny@stuntrocket.co
    volumes:
      - /srv/dev-disk-by-label-shared/appdata/letsencrypt:/config
    ports:
      - 443:443
      - 82:80
    networks:
      - laravel
    restart: unless-stopped

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php
    volumes:
      - /srv/dev-disk-by-label-shared/appdata/laravel/src:/var/www/html:delegated
    ports:
      - "9000:9000"
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - /srv/dev-disk-by-label-shared/appdata/laravel/src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - laravel

  npm:
    image: node:13.7
    container_name: npm
    volumes:
      - /srv/dev-disk-by-label-shared/appdata/laravel/src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["npm"]

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: artisan
    volumes:
      - /srv/dev-disk-by-label-shared/appdata/laravel/src:/var/www/html:delegated
    depends_on:
      - mariadb
    working_dir: /var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
    networks:
      - laravel

  scheduler:
    image: composer:latest
    container_name: laravel-scheduler
    depends_on:
      - php
    volumes:
      - /srv/dev-disk-by-label-shared/appdata/laravel/src:/var/www/html
    environment:
      APP_ENV: local
      CONTAINER_ROLE: scheduler

  queue:
    image: composer:latest
    container_name: laravel-queue
    depends_on:
      - php
    volumes:
      - /srv/dev-disk-by-label-shared/appdata/laravel/src:/var/www/html
    environment:
      APP_ENV: local
      CONTAINER_ROLE: queue

volumes:
  databases:
